package com.hzzl.sg.model;

import java.util.Date;

/**
* @Program:
* @Description: ${description}
* @Author: MaQingFu
* @Date: 2018/7/26 15:02
**/
public class Flight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.master_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String masterNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.flight_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Integer flightNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.house_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String houseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.port_start
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String portStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.port_end
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String portEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.batch_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String batchNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.launch_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Date launchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.arrive_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Date arriveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.creater
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.create_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.update_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.id
     *
     * @return the value of flight.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.id
     *
     * @param id the value for flight.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.master_number
     *
     * @return the value of flight.master_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getMasterNumber() {
        return masterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.master_number
     *
     * @param masterNumber the value for flight.master_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setMasterNumber(String masterNumber) {
        this.masterNumber = masterNumber == null ? null : masterNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.flight_number
     *
     * @return the value of flight.flight_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Integer getFlightNumber() {
        return flightNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.flight_number
     *
     * @param flightNumber the value for flight.flight_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setFlightNumber(Integer flightNumber) {
        this.flightNumber = flightNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.house_name
     *
     * @return the value of flight.house_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getHouseName() {
        return houseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.house_name
     *
     * @param houseName the value for flight.house_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setHouseName(String houseName) {
        this.houseName = houseName == null ? null : houseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.port_start
     *
     * @return the value of flight.port_start
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getPortStart() {
        return portStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.port_start
     *
     * @param portStart the value for flight.port_start
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setPortStart(String portStart) {
        this.portStart = portStart == null ? null : portStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.port_end
     *
     * @return the value of flight.port_end
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getPortEnd() {
        return portEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.port_end
     *
     * @param portEnd the value for flight.port_end
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setPortEnd(String portEnd) {
        this.portEnd = portEnd == null ? null : portEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.batch_number
     *
     * @return the value of flight.batch_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getBatchNumber() {
        return batchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.batch_number
     *
     * @param batchNumber the value for flight.batch_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber == null ? null : batchNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.launch_time
     *
     * @return the value of flight.launch_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Date getLaunchTime() {
        return launchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.launch_time
     *
     * @param launchTime the value for flight.launch_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setLaunchTime(Date launchTime) {
        this.launchTime = launchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.arrive_time
     *
     * @return the value of flight.arrive_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Date getArriveTime() {
        return arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.arrive_time
     *
     * @param arriveTime the value for flight.arrive_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setArriveTime(Date arriveTime) {
        this.arriveTime = arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.creater
     *
     * @return the value of flight.creater
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.creater
     *
     * @param creater the value for flight.creater
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.create_time
     *
     * @return the value of flight.create_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.create_time
     *
     * @param createTime the value for flight.create_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.update_time
     *
     * @return the value of flight.update_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.update_time
     *
     * @param updateTime the value for flight.update_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}