package com.hzzl.sg.model;

/**
* @program: SG
* @description: ${description}
* @Author: MaQingFu
* @Date: 2018/7/26 15:02
**/
public class House {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.house_code
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String houseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.house_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String houseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.nation_code
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String nationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.contacts
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.contacts_phone
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String contactsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.house_status
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Integer houseStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.contacts_address
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String contactsAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.id
     *
     * @return the value of house.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.id
     *
     * @param id the value for house.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.house_code
     *
     * @return the value of house.house_code
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getHouseCode() {
        return houseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.house_code
     *
     * @param houseCode the value for house.house_code
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setHouseCode(String houseCode) {
        this.houseCode = houseCode == null ? null : houseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.house_name
     *
     * @return the value of house.house_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getHouseName() {
        return houseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.house_name
     *
     * @param houseName the value for house.house_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setHouseName(String houseName) {
        this.houseName = houseName == null ? null : houseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.nation_code
     *
     * @return the value of house.nation_code
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getNationCode() {
        return nationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.nation_code
     *
     * @param nationCode the value for house.nation_code
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setNationCode(String nationCode) {
        this.nationCode = nationCode == null ? null : nationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.contacts
     *
     * @return the value of house.contacts
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.contacts
     *
     * @param contacts the value for house.contacts
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.contacts_phone
     *
     * @return the value of house.contacts_phone
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getContactsPhone() {
        return contactsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.contacts_phone
     *
     * @param contactsPhone the value for house.contacts_phone
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setContactsPhone(String contactsPhone) {
        this.contactsPhone = contactsPhone == null ? null : contactsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.house_status
     *
     * @return the value of house.house_status
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Integer getHouseStatus() {
        return houseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.house_status
     *
     * @param houseStatus the value for house.house_status
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setHouseStatus(Integer houseStatus) {
        this.houseStatus = houseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.contacts_address
     *
     * @return the value of house.contacts_address
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getContactsAddress() {
        return contactsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.contacts_address
     *
     * @param contactsAddress the value for house.contacts_address
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setContactsAddress(String contactsAddress) {
        this.contactsAddress = contactsAddress == null ? null : contactsAddress.trim();
    }
}