package com.hzzl.sg.model;

import java.util.Date;

/**
* @Program: SG
* @Description: ${description}
* @Author: MaQingFu
* @Date: 2018/7/26 15:08 
**/
public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.owner_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String ownerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.house_id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.outhouse_classify
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String outhouseClassify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.master_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String masterNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.batch_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String batchNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.express_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String expressNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.express_type
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String expressType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.receiver_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_count
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Integer goodsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.package_weight
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Double packageWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.repeat_weight
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Double repeatWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_from
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String orderFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_number
     *
     * @return the value of order.order_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_number
     *
     * @param orderNumber the value for order.order_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.owner_name
     *
     * @return the value of order.owner_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.owner_name
     *
     * @param ownerName the value for order.owner_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.house_id
     *
     * @return the value of order.house_id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.house_id
     *
     * @param houseId the value for order.house_id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.outhouse_classify
     *
     * @return the value of order.outhouse_classify
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getOuthouseClassify() {
        return outhouseClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.outhouse_classify
     *
     * @param outhouseClassify the value for order.outhouse_classify
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setOuthouseClassify(String outhouseClassify) {
        this.outhouseClassify = outhouseClassify == null ? null : outhouseClassify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.master_number
     *
     * @return the value of order.master_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getMasterNumber() {
        return masterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.master_number
     *
     * @param masterNumber the value for order.master_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setMasterNumber(String masterNumber) {
        this.masterNumber = masterNumber == null ? null : masterNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.batch_number
     *
     * @return the value of order.batch_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getBatchNumber() {
        return batchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.batch_number
     *
     * @param batchNumber the value for order.batch_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber == null ? null : batchNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.express_number
     *
     * @return the value of order.express_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getExpressNumber() {
        return expressNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.express_number
     *
     * @param expressNumber the value for order.express_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setExpressNumber(String expressNumber) {
        this.expressNumber = expressNumber == null ? null : expressNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.express_type
     *
     * @return the value of order.express_type
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getExpressType() {
        return expressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.express_type
     *
     * @param expressType the value for order.express_type
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setExpressType(String expressType) {
        this.expressType = expressType == null ? null : expressType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.receiver_name
     *
     * @return the value of order.receiver_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.receiver_name
     *
     * @param receiverName the value for order.receiver_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_count
     *
     * @return the value of order.goods_count
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_count
     *
     * @param goodsCount the value for order.goods_count
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.package_weight
     *
     * @return the value of order.package_weight
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Double getPackageWeight() {
        return packageWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.package_weight
     *
     * @param packageWeight the value for order.package_weight
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setPackageWeight(Double packageWeight) {
        this.packageWeight = packageWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.repeat_weight
     *
     * @return the value of order.repeat_weight
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Double getRepeatWeight() {
        return repeatWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.repeat_weight
     *
     * @param repeatWeight the value for order.repeat_weight
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setRepeatWeight(Double repeatWeight) {
        this.repeatWeight = repeatWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_status
     *
     * @return the value of order.order_status
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_status
     *
     * @param orderStatus the value for order.order_status
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_from
     *
     * @return the value of order.order_from
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getOrderFrom() {
        return orderFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_from
     *
     * @param orderFrom the value for order.order_from
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setOrderFrom(String orderFrom) {
        this.orderFrom = orderFrom == null ? null : orderFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @return the value of order.update_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_time
     *
     * @param updateTime the value for order.update_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}