package com.hzzl.sg.model;

/**
* @Program: SG
* @Description: ${description}
* @Author: MaQingFu
* @Date: 2018/7/26 15:34
**/
public class Settings {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_settings.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_settings.user_id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_settings.setting_1
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String setting1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_settings.id
     *
     * @return the value of sys_settings.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_settings.id
     *
     * @param id the value for sys_settings.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_settings.user_id
     *
     * @return the value of sys_settings.user_id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_settings.user_id
     *
     * @param userId the value for sys_settings.user_id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_settings.setting_1
     *
     * @return the value of sys_settings.setting_1
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getSetting1() {
        return setting1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_settings.setting_1
     *
     * @param setting1 the value for sys_settings.setting_1
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setSetting1(String setting1) {
        this.setting1 = setting1 == null ? null : setting1.trim();
    }
}