package com.hzzl.sg.model;

import java.util.Date;

/**
* @Program: SG
* @Description: ${description}
* @Author: MaQingFu
* @Date: 2018/7/26 15:22
**/
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.real_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.role_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Integer phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_status
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_role
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.house_authority
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String houseAuthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.owner_authority
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private String ownerAuthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.real_name
     *
     * @return the value of sys_user.real_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.real_name
     *
     * @param realName the value for sys_user.real_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.role_name
     *
     * @return the value of sys_user.role_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.role_name
     *
     * @param roleName the value for sys_user.role_name
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone_number
     *
     * @return the value of sys_user.phone_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Integer getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone_number
     *
     * @param phoneNumber the value for sys_user.phone_number
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setPhoneNumber(Integer phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_status
     *
     * @return the value of sys_user.user_status
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_status
     *
     * @param userStatus the value for sys_user.user_status
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_role
     *
     * @return the value of sys_user.user_role
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_role
     *
     * @param userRole the value for sys_user.user_role
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole == null ? null : userRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.house_authority
     *
     * @return the value of sys_user.house_authority
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getHouseAuthority() {
        return houseAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.house_authority
     *
     * @param houseAuthority the value for sys_user.house_authority
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setHouseAuthority(String houseAuthority) {
        this.houseAuthority = houseAuthority == null ? null : houseAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.owner_authority
     *
     * @return the value of sys_user.owner_authority
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public String getOwnerAuthority() {
        return ownerAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.owner_authority
     *
     * @param ownerAuthority the value for sys_user.owner_authority
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setOwnerAuthority(String ownerAuthority) {
        this.ownerAuthority = ownerAuthority == null ? null : ownerAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_time
     *
     * @return the value of sys_user.update_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_time
     *
     * @param updateTime the value for sys_user.update_time
     *
     * @mbggenerated Thu Jul 26 14:31:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}